//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENXE()
        {
            this.LAIs = new HashSet<LAI>();
        }
    
        public int IDChuyen { get; set; }
        public Nullable<System.TimeSpan> GioKhoiHanh { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<int> IDTuyenDuong { get; set; }
    
        public virtual TUYENDUONG TUYENDUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAI> LAIs { get; set; }
    }
}
