//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXETHUCTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENXETHUCTE()
        {
            this.DATVEs = new HashSet<DATVE>();
        }
    
        public int IDChuyenXe { get; set; }
        public string GioKhoiHanh { get; set; }
        public string NgayKhoiHanh { get; set; }
        public Nullable<int> IDXe { get; set; }
        public string IDTaiXe1 { get; set; }
        public string IDTaiXe2 { get; set; }
    
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATVE> DATVEs { get; set; }
    }
}
