//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbQLBanVeXeKhachContext : DbContext
    {
        public DbQLBanVeXeKhachContext()
            : base("name=DbQLBanVeXeKhachContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BEN> BENs { get; set; }
        public virtual DbSet<CHUYENXE> CHUYENXEs { get; set; }
        public virtual DbSet<CHUYENXETHUCTE> CHUYENXETHUCTEs { get; set; }
        public virtual DbSet<DATVE> DATVEs { get; set; }
        public virtual DbSet<DATVE_SOGHE> DATVE_SOGHE { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LAI> LAIs { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<NHANSU> NHANSUs { get; set; }
        public virtual DbSet<SODIENTHOAI> SODIENTHOAIs { get; set; }
        public virtual DbSet<TUYENDUONG> TUYENDUONGs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    }
}
