//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbQLBanVeXeKhachContext : DbContext
    {
        public DbQLBanVeXeKhachContext()
            : base("name=DbQLBanVeXeKhachContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BEN> BENs { get; set; }
        public virtual DbSet<CHUYENXE> CHUYENXEs { get; set; }
        public virtual DbSet<CHUYENXETHUCTE> CHUYENXETHUCTEs { get; set; }
        public virtual DbSet<DATVE> DATVEs { get; set; }
        public virtual DbSet<DATVE_SOGHE> DATVE_SOGHE { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LAI> LAIs { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<NHANSU> NHANSUs { get; set; }
        public virtual DbSet<SODIENTHOAI> SODIENTHOAIs { get; set; }
        public virtual DbSet<TUYENDUONG> TUYENDUONGs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    
        public virtual ObjectResult<Nullable<bool>> sp_ThemMoiBen(string maBen, string tenBen)
        {
            var maBenParameter = maBen != null ?
                new ObjectParameter("MaBen", maBen) :
                new ObjectParameter("MaBen", typeof(string));
    
            var tenBenParameter = tenBen != null ?
                new ObjectParameter("TenBen", tenBen) :
                new ObjectParameter("TenBen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_ThemMoiBen", maBenParameter, tenBenParameter);
        }
    
        public virtual ObjectResult<BEN> sp_SelectAllBenXe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BEN>("sp_SelectAllBenXe");
        }
    
        public virtual ObjectResult<BEN> sp_SelectAllBenXe(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BEN>("sp_SelectAllBenXe", mergeOption);
        }
    
        public virtual ObjectResult<TUYENDUONG> sp_GetTuyenDuongByDiemKhoiHanh(string iDDiemKhoiHanh)
        {
            var iDDiemKhoiHanhParameter = iDDiemKhoiHanh != null ?
                new ObjectParameter("IDDiemKhoiHanh", iDDiemKhoiHanh) :
                new ObjectParameter("IDDiemKhoiHanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TUYENDUONG>("sp_GetTuyenDuongByDiemKhoiHanh", iDDiemKhoiHanhParameter);
        }
    
        public virtual ObjectResult<TUYENDUONG> sp_GetTuyenDuongByDiemKhoiHanh(string iDDiemKhoiHanh, MergeOption mergeOption)
        {
            var iDDiemKhoiHanhParameter = iDDiemKhoiHanh != null ?
                new ObjectParameter("IDDiemKhoiHanh", iDDiemKhoiHanh) :
                new ObjectParameter("IDDiemKhoiHanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TUYENDUONG>("sp_GetTuyenDuongByDiemKhoiHanh", mergeOption, iDDiemKhoiHanhParameter);
        }
    
        public virtual ObjectResult<sp_GetTuyenDuongByDiemKhoiHanh2_Result> sp_GetTuyenDuongByDiemKhoiHanh2(string iDDiemKhoiHanh)
        {
            var iDDiemKhoiHanhParameter = iDDiemKhoiHanh != null ?
                new ObjectParameter("IDDiemKhoiHanh", iDDiemKhoiHanh) :
                new ObjectParameter("IDDiemKhoiHanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTuyenDuongByDiemKhoiHanh2_Result>("sp_GetTuyenDuongByDiemKhoiHanh2", iDDiemKhoiHanhParameter);
        }
    
        public virtual ObjectResult<CHUYENXE> sp_GetChuyenXeByTuyenDuong(Nullable<int> iDTuyenDuong)
        {
            var iDTuyenDuongParameter = iDTuyenDuong.HasValue ?
                new ObjectParameter("IDTuyenDuong", iDTuyenDuong) :
                new ObjectParameter("IDTuyenDuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHUYENXE>("sp_GetChuyenXeByTuyenDuong", iDTuyenDuongParameter);
        }
    
        public virtual ObjectResult<CHUYENXE> sp_GetChuyenXeByTuyenDuong(Nullable<int> iDTuyenDuong, MergeOption mergeOption)
        {
            var iDTuyenDuongParameter = iDTuyenDuong.HasValue ?
                new ObjectParameter("IDTuyenDuong", iDTuyenDuong) :
                new ObjectParameter("IDTuyenDuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHUYENXE>("sp_GetChuyenXeByTuyenDuong", mergeOption, iDTuyenDuongParameter);
        }
    }
}
